
GET http://localhost:5099/games

###

GET http://localhost:5099/games/2

###

POST http://localhost:5099/games
Content-Type: application/json

{
    "name" : "MinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraft",
    "genre" : "Kids",
    "price" : 101,
    "releaseDate" : "2011-08-01"
}

###

PUT http://localhost:5099/games/4
Content-Type: application/json

{
    "name": "Street Figther",
    "genre": "Fight",
    "price": 300,
    "releaseDate": "2002-01-07"
}

###

DELETE http://localhost:5099/games/2

